FlowFuse/driver-k8s

.eslintrc
kubernetes.js
package-lock.json
package.json

Add Linter

---

kubernetes.js
package.json

Update version to 0.1.1

---

kubernetes.js

Also add annotaions for AWS ALB

Match url schema to base_url

---

package-lock.json
package.json

This should close out some of the security warnings

Bump kube client version to pick up deps

---

kubernetes.js

This will need https://github.com/flowforge/flowforge/pull/352 to be merged first - as that takes over responsibility for setting this values

Stop driver setting baseURL/forgeURL

---

kubernetes.js

pulls container name and memory/cpu limits from stack info

Add stack support

---

README.md
kubernetes.js

Fixes #1 
Fixes #18 
Includes README.md update to show configuration options.

Allow Node selectors to be set in flowforge.yml

---

kubernetes.js

Also add in imagePullSecret for projects

Fix CPU % Validator regex

---

CHANGELOG.md
kubernetes.js
package.json

Back port stack fixes that got lost in 0.3 release

Stack fix 0.3 backport

---

kubernetes.js

Still trying to work out how it happened, but this should prevent the failure.

Deal with project not in internal cache

---

kubernetes.js

Also prevent time out on creating new project.

Fix ingress annotations on AWS

---

kubernetes.js

Force K8s to pull if the container hash has changed.
fixes #32

Ensure latest version of contianer is always pulled

---

kubernetes.js

Also apply lint rule to ignore ignored error for now

Add description to stack properties

---

kubernetes.js

Add FORGE_NR_SECRET env if project has credSecret set

---

kubernetes.js

Part of https://github.com/flowforge/flowforge/issues/442
Adds `logoutNodeRED` to kubernetes.js
All related PRs ...
1. https://github.com/flowforge/flowforge/pull/643
1. https://github.com/flowforge/flowforge-driver-localfs/pull/48
1. https://github.com/flowforge/flowforge-nr-launcher/pull/40
1. https://github.com/flowforge/flowforge-driver-docker/pull/24
1. https://github.com/flowforge/flowforge-driver-k8s/pull/39

Map FlowForge logout to nodered auth/revoke

---

kubernetes.js

Fixes https://github.com/flowforge/flowforge/issues/586

Add startup check for status

---

kubernetes.js

Part of https://github.com/flowforge/flowforge/pull/706
This passes through the broker credentials to the launcher - if they are set.

Add FORGE_BROKER_* credentials to launcher env

---

kubernetes.js

see https://github.com/flowforge/flowforge-nr-launcher/pull/59

Add licenseType to launcher env

---

kubernetes.js

Since project.name can now be uppercase

Make use of project.safename

---

kubernetes.js

And prevent Privilege escalation

Force container to run as UID 1000

---

.eslintrc
.github/workflows/build.yml
kubernetes.js
package.json

- Update to latest eslint
- Makes object-shorthand an error
- Adds default build action (linting only)

Update eslint rules

---

kubernetes.js

Only set the nodeSelector if in options

---

kubernetes.js

part of flowforge/flowforge#999

Add flags to inhibit TCP/UDP inbound connections

---

kubernetes.js

Containers won't start if env var values are not strings

Env Var values must be strings

---

kubernetes.js

part of https://github.com/flowforge/flowforge/issues/1194
Will allow defaults to be set from driver.options.default_stack in config yaml

Add getDefaultStackProperies

---

CHANGELOG.md
kubernetes.js
package.json

Remove AWS ALB specific annotations & 1.3.3 release information

---

kubernetes.js

Project gets stuck in "starting" state after it has been running successfully for multiple days
- [-] Suitable unit/system level tests have been added and they pass
- [-] Documentation has been updated
- [-] Upgrade instructions
- [-] Configuration details
- [-] Concepts
- [-] Changes `flowforge.yml`?
- [-] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
- [-] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production
- [-] Backport needed? -> add the `backport` label
- [-] Includes a DB migration? -> add the `area:migration` label

Fix deployment state

---

CHANGELOG.md
package.json

- Update CHANGELOG for 1.6.0
- Update version to 1.6.0

Release 1.6.0

---

.github/workflows/build.yml
.github/workflows/project-automation.yml
.github/workflows/release-publish.yml
.gitignore
package-lock.json

See https://github.com/flowforge/flowforge-dev-env/issues/20
Best viewed with ?w=1, VSCode fixed the indenting: https://github.com/flowforge/flowforge-driver-k8s/pull/89/files?w=1

Add package-lock.json

---

kubernetes.js

part of flowforge/flowforge#2240
Allow the domain bound to instances to be changed.
This does require the forge app to run on both old/new domain as existing instances will need access old domain
flowforge/flowforge#2240

Support for changing the base domain

---

.github/workflows/build.yml
.github/workflows/publish.yml

Introduce package publish pipeline

Introduce package publish pipeline

---

package-lock.json
package.json

fixes #106
Bump to pick up fixed dependencies 
#106

Bump kubernetes client

---

.github/workflows/publish.yml

Add flowforge container build dispatch in the node package build pipeline .

Add flowforge container build dispatch in the node package build pipeline

---

kubernetes.js

part of FlowFuse/flowfuse#2755
Passes the CPU and memory limits to the container (and hence nr-launcher)
FlowFuse/flowfuse#2755

Expose mem/cpu limits

---

CHANGELOG.md
package-lock.json
package.json

Bump version number and update Changelog

Update version for 1.12.1 release

---

CHANGELOG.md
package-lock.json
package.json

- Update Changelog
- update versions in package.json

Bump version for v2.0.1

---

README.md
kubernetes.js

Remove hard coded `securityContext` so pods will run on OpenShift

Make NR pods run on OpenShift

---

kubernetes.js

We left the code for creating raw pods when we moved to creating deployments.
This is to prevent confusion when making updates to the k8s artefacts (e.g. making changes to the unused `createPod()` code

Remove legacy code that is not used anymore

---

kubernetes.js

Code was doing a sting concatenation not an addition

Fix memory addition

---

kubernetes.js

Reverts FlowFuse/driver-k8s#150
Implementing this in `/settings` api endpoint in the forge app https://github.com/FlowFuse/flowfuse/blob/main/forge/routes/api/project.js#L798 as suggested in the [comments](https://github.com/FlowFuse/flowfuse/issues/3578#issuecomment-2088639066).

Revert "Add support for user set health check interval"

---

.github/workflows/release-publish.yml

Update release-publish.yml to use NodeJS 18

---

kubernetes.js

Add a bit more debug to make it easier to debug OpenShift problems

Add better logging for when running on OpenShift

---

kubernetes.js

Add test to see if 3rd Party Broker credentials table is present before trying to start MQTT-Schema-Agents

Add test to see if 3rd party broker table is present

---

kubernetes.js

Ensure mqtt-status-agents run on correct k8s nodes

Add node selector to mqtt-schema-agent

---

CHANGELOG.md
package-lock.json
package.json

- **Update CHANGELOG for 2.16.0**
- **Update version to 2.16.0**

Release 2.16.0

---

kubernetes.js

part of FlowFuse/flowfuse#5523
Returns historical CPU and process size info
FlowFuse/flowfuse#5523

Add Resources API endpoint

---

CHANGELOG.md
package-lock.json
package.json

- **Update CHANGELOG for 2.19.0**
- **Update version to 2.19.0**

Release 2.19.0
