kubernetes.js

so it is bound to the same entry point as the management app

Add project to ALB group 

---

kubernetes.js

Fix typo in pod limits

---

kubernetes.js

This updates the k8s driver to the new driver API introduced by flowforge/flowforge#437
- API changed to support stopping a project without clearing its resources (ie 'suspended' state)
- Keeps internal track of the container state, so we can avoid trying to polling the launcher if we don't think it is ready

Update to new driver api and lifecycle

---

kubernetes.js

This adds proper error handling in the case where the platform asks the driver to perform actions on a project it doesn't know about. That state should not be possible to get into, but https://github.com/flowforge/flowforge/issues/612 revealed a case where it was possible (although https://github.com/flowforge/flowforge/pull/663 should plug that gap).

Throw proper errors when actions performed on unknown project

---

kubernetes.js

part of https://github.com/flowforge/flowforge/issues/662
Team ID hash is required in launcher ~ settings.js file for querying list of projects in the team.

add env var FORGE_TEAM_ID

---

kubernetes.js

part of [When a project is started/restarted launcher details not populated#990](https://github.com/flowforge/flowforge/issues/990)
related:  [Npm install starting #75](https://github.com/flowforge/flowforge-nr-launcher/pull/75)
Align operations with localfs and docker drivers by removing the direct status polling to node-red and instead, only use the `flowforge/info` for polling status

Improve project status & detail reporting to frontend

---

kubernetes.js

Alternative to #68 
The K8s Driver currently creates bare Pods which are not automatically migrated to new a Node when the current Node is shutdown, this prevents migration as part of upgrades and in case of AWS/Hardware failures.
This PR only upgrades from bare Pod to Deployment if the project is suspended and restarted.
New projects are created as Deployment
If the driver finds a missing project at startup it will recreate it as a Deployment.
- [-] Documentation has been updated
- [-] Upgrade instructions
- [-] Configuration details
- [-] Concepts
- [-] Changes `flowforge.yml`?
- [-] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
- [-] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production
- [-] Backport needed? -> add the `backport` label …

Pod to deployment gradual

---

kubernetes.js

Remove the ALB annotations as moving to Nginx ingress even on AWS EKS
Manual back port done as #73

Remove ALB annotations

---

kubernetes.js

fixes #75
Log failure to create Service and Ingress objects if project is not starting from being suspended.
#75

Log failures if not restarting susspended project

---

kubernetes.js

Sets the correct number of replicas on the Deployment object
Also has support for merging the logs from multiple replicas
To do:
flowforge/flowforge#2156

HA: multiple instance replicas

---

kubernetes.js

Added websocket annotation for nginx ingress k8s
added the nginx annotation for websocket support in k8s
[(https://github.com/flowforge/flowforge-driver-k8s/issues/83)](https://github.com/flowforge/flowforge-driver-k8s/issues/83)

Added support for annotation substitutions

---

kubernetes.js

Suspended instances didn't used to delete ingress and service objects, which could lead to problems with nodeport services.
Since we automatically try and recreate both the service and ingress when restarting a suspended instance, no reason not to remove them.
#97

Remove evreything on suspend

---

kubernetes.js

fixes #97 
Change the default Service Type to ClusterIP from NodePort to prevent exhausting NodePort range
#97

Move to CluserIP

---

kubernetes.js

[Race on eventually consistent operations of provision/deprovision of Project's k8s resources [e.g. service, ingress]](https://github.com/FlowFuse/driver-k8s/issues/114)

Fix creation race 114

---

README.md
kubernetes.js
package-lock.json
package.json

possible for creating/deleting k8s artefacts to fail if done out of order or too quickly.
#114

Run promises in order

---

kubernetes.js

fixes #121
Values for resource limits are added as numbers but later versions of K8s require all env vars to be strings.
#121

Force Resource limits to Strings

---

kubernetes.js

As discussed in https://github.com/FlowFuse/flowfuse/issues/3174, allow the Project instance CPU quota to exceed 1 CPU (with this PR, up to 10 CPU)
https://github.com/FlowFuse/flowfuse/issues/3174
Looks like there's no test specific to this regex?

#3174: Enable Multi-Core CPU Support for Node-RED Projects

---

README.md
kubernetes.js

Allows k8s to issue certificates for instances with cert-manager.io automatically (supports lets encrypt and private internal CAs)

Add support for using cert manager

---

kubernetes.js

Typo, extra `_` in option name

---

kubernetes.js

Typo, missing an `s` from the end of `requests`
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#example-1

Fix containers resource requests missing last s

---

README.md
kubernetes.js

part of FlowFuse/flowfuse#3324
Allows NR Pods to be configured to output NR logs to stdout
FlowFuse/flowfuse#3324

Add log passthrough support

---

kubernetes.js

part of FlowFuse/admin#212
Rename from flowforge/node-red to flowfuse/node-red
FlowFuse/admin#212

Rename default stack container

---

kubernetes.js

part of https://github.com/FlowFuse/flowfuse/issues/3630
This allows npm/nr-launcher to use up to 128m more than the Stack memory constraint.
Since the nr-launcher set the --max-old-space setting to 75% of the Stack memory this will limit the Node-RED process to not use this extra memory allowance.
As this is set as the k8s resource `limits` and not the `requests` it should not impact the number of Instances that can be scheduled on a node.
https://github.com/FlowFuse/flowfuse/issues/3630

Allow pods to use 128m extra memory for npm

---

kubernetes.js

closes #149
Maps `healthCheckInterval` into settings so that a user set value can be passed to the `Launcher.start` call
NOTES:
* Can be approved any time, but should only be merged once all related PRs are approved:
* https://github.com/FlowFuse/flowfuse/pull/3716
* https://github.com/FlowFuse/driver-localfs/pull/124
* https://github.com/FlowFuse/driver-docker/pull/92
* https://github.com/FlowFuse/nr-launcher/pull/228
#149

Add support for user set health check interval

---

README.md
kubernetes.js

part of flowfuse/flowfuse#324
Adds support to create the extra ingress object for an intances custom hostname
flowfuse/flowfuse#324

Custom Hostname support

---

README.md
kubernetes.js
lib/aws-efs.js
package-lock.json
package.json
templates.js

fixes FlowFuse/flowfuse#4003
Adds support for mounting a PVC on `/data/storage` to allow for using the standard filesystem nodes.
Also refactors all K8s templates into their own file to make things a little cleaner.
FlowFuse/flowfuse#4003

Persistent storage

---

lib/aws-efs.js

Make sure the right EFS filesystem is picked. By default the tool only returns the first 100 APs
NA

Ensure full count of EFS AccessPoints

---

kubernetes.js
package-lock.json
package.json

Adds the driver interface to https://github.com/FlowFuse/nr-launcher/issues/273

First pass at file api for k8s

---

README.md
kubernetes.js

This pull request adds the possibility of specifying a custom [pod security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) for launched deployments.
https://github.com/FlowFuse/helm/issues/526

feat: Add possibility to specify custom pod security context

---

kubernetes.js
templates.js

part of flowfuse/flowfuse#4969
Adds support for starting/stopping MQTT-Schema-Agent on Kubernetes

Mqtt schema agent

---

kubernetes.js

Fix await when polling mqtt-schema-agent status

Fix await when polling mqtt-schema-agent status

---

kubernetes.js

Add check to only restart MQTT Schema agents that are in running state if missing on start up.

Only restart active MQTT Agents

---

README.md
kubernetes.js
templates.js

This pull request adds a possibility to define service type which is created for NodeRED instance deployment. Currently, only `ClusterIP` (default) and `NodePort` service types are supported.
Closes https://github.com/FlowFuse/flowfuse/issues/4041

feat: Add possibility to customise service type created for project deployment

---

README.md
kubernetes.js

This pull request adds an option to provide a list of custom labels, via `projectLabels` configuration parameter, that will be applied to all project-related resources. 
https://github.com/FlowFuse/helm/issues/682

feat: add possibility to apply custom labels on project-related resources
